version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: