name: Python application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: yourdbname
          POSTGRES_USER: youruser
          POSTGRES_PASSWORD: yourpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add your test commands here, e.g., pytest

    - name: Build Docker image
      run: |
        docker build -t myapp:${{ github.sha }} .

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image to GitHub Packages
      run: |
        docker tag myapp:${{ github.sha }} ghcr.io/meenakshibhat1998/poster-kata:${{ github.sha }}
        docker push ghcr.io/meenakshibhat1998/poster-kata:${{ github.sha }}